"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { places } from "@/data/places";

const moods=["Спокойно","Романтика","Вдохновиться","Удивиться"];
const budgets=["Бесплатно","300–1500 ₽","2000–5000 ₽","6000–10000 ₽","от 10000 ₽"];
const companies=["Один","Пара","Друзья","Семья"];
const durations=["До 1 часа","1–2 часа","2–4 часа","Полдня"];
const interests=["Искусство","Вкусно поесть","Прогулки","Необычные места","Развлечения"];
type Step=1|2|3|4|5|6;

export default function SurprisePage(){
 const [step,setStep]=useState<Step>(1),[mood,setMood]=useState(""),[budget,setBudget]=useState(""),[company,setCompany]=useState(""),[duration,setDuration]=useState(""),[interest,setInterest]=useState(""),[generated,setGenerated]=useState(false),[invite,setInvite]=useState(false);
 const matchingPlaces=useMemo(()=>places.map(p=>{let score=0;if(p.mood===mood)score+=4;if(p.budget===budget)score+=3;if(p.company.includes(company))score+=3;if(p.duration===duration)score+=2;const c=p.category.toLowerCase();if(interest==="Искусство"&&(c.includes("искус")||c.includes("музей")))score+=3;if(interest==="Вкусно поесть"&&(c.includes("каф")||c.includes("ресторан")||c.includes("коф")||c.includes("бар")))score+=3;if(interest==="Прогулки"&&(c.includes("прогул")||c.includes("парк")||c.includes("пространство")))score+=3;if(interest==="Необычные места"&&(c.includes("необыч")||c.includes("скрыт")||c.includes("андеграунд")))score+=3;if(interest==="Развлечения"&&(c.includes("развлеч")||c.includes("интерактив")))score+=3;return{...p,score};}).sort((a,b)=>b.score-a.score).slice(0,3),[mood,budget,company,duration,interest]);
 const selected=[mood,company,budget,duration,interest]; const can=()=>step===1?!!mood:step===2?!!company:step===3?!!budget:step===4?!!duration:step===5?!!interest:true;
 const Option=({value,current,set}:{value:string;current:string;set:(v:string)=>void})=><button type="button" onClick={()=>set(value)} className={`rounded-[22px] border px-5 py-5 text-left text-base sm:text-lg font-medium transition ${current===value?"bg-black border-black text-white":"bg-white border-black/10 hover:border-black/30"}`}><span className="flex justify-between gap-3"><span>{value}</span><span>{current===value?"✓":""}</span></span></button>;
 const question=step===1?["Какое у тебя настроение?",moods,mood,setMood]:step===2?["Какая сегодня компания?",companies,company,setCompany]:step===3?["Какой бюджет?",budgets,budget,setBudget]:step===4?["Сколько времени есть?",durations,duration,setDuration]:["Чего хочется больше?",interests,interest,setInterest] as any;
 const reset=()=>{setGenerated(false);setStep(1);setMood("");setBudget("");setCompany("");setDuration("");setInterest("");setInvite(false);window.scrollTo({top:0,behavior:"smooth"});};
 return <main className="min-h-screen bg-[#f7f4ef] pt-32 pb-24"><section className="max-w-6xl mx-auto px-4 sm:px-6"><div className="max-w-3xl"><div className="inline-flex rounded-full bg-black text-white px-4 py-2 text-sm">✦ ALMA · Удиви меня</div><h1 className="mt-7 text-5xl sm:text-6xl lg:text-7xl font-bold tracking-tight leading-[.98]">Соберём твой<br/>Петербург</h1><p className="mt-6 max-w-2xl text-lg sm:text-xl leading-8 text-neutral-500">Ответь на несколько вопросов — ALMA соберёт не просто список мест, а сценарий прогулки.</p></div>
 {!generated&&<div className="mt-14 sm:mt-20"><div className="flex justify-between mb-3 text-sm text-neutral-500"><span>Шаг {step} из 6</span><span>{Math.round(step/6*100)}%</span></div><div className="h-1.5 rounded-full bg-black/5 overflow-hidden"><div className="h-full bg-black transition-all" style={{width:`${step/6*100}%`}}/></div><div className="mt-8 rounded-[40px] bg-[#ebe6de] p-6 sm:p-10">
 {step<6?<><p className="text-sm text-neutral-500">{step===5?"Последний штрих":"Удиви меня"}</p><h2 className="mt-3 text-3xl sm:text-4xl font-bold">{question[0] as string}</h2><div className="mt-8 grid sm:grid-cols-2 gap-3">{(question[1] as string[]).map(v=><Option key={v} value={v} current={question[2] as string} set={question[3] as (v:string)=>void}/>)}</div></>:<><p className="text-sm text-neutral-500">Всё готово</p><h2 className="mt-3 text-3xl sm:text-4xl font-bold">Собираем маршрут?</h2><div className="mt-8 grid sm:grid-cols-2 gap-3">{[["Настроение",mood],["Компания",company],["Бюджет",budget],["Время",duration],["Хочется",interest]].map(([l,v])=><div key={l} className="rounded-[22px] bg-white p-5"><p className="text-xs uppercase tracking-wider text-neutral-400">{l}</p><p className="mt-2 font-semibold">{v}</p></div>)}</div></>}
 <div className="mt-9 flex justify-between gap-3"><button disabled={step===1} onClick={()=>setStep((step-1) as Step)} className="rounded-full px-6 py-3.5 border border-black/10 disabled:opacity-30">← Назад</button>{step<6?<button disabled={!can()} onClick={()=>setStep((step+1) as Step)} className="rounded-full bg-black text-white px-7 py-3.5 disabled:opacity-25">Дальше →</button>:<button onClick={()=>setGenerated(true)} className="rounded-full bg-black text-white px-8 py-3.5">✦ Создать маршрут</button>}</div></div></div>}
 {generated&&<section className="mt-16"><div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-5"><div><p className="text-xs uppercase tracking-[.22em] text-neutral-500">Твой маршрут</p><h2 className="mt-4 text-4xl sm:text-6xl font-bold">Кажется, тебе сюда</h2><p className="mt-4 text-neutral-500">{selected.filter(Boolean).join(" · ")}</p></div><button onClick={reset} className="self-start rounded-full bg-white border border-black/10 px-6 py-3">✦ Удиви меня ещё раз</button></div>
 <div className="mt-9 rounded-[34px] overflow-hidden border border-black/5 bg-[#ded8ce]"><div className="relative h-[330px] sm:h-[430px] p-6 sm:p-10 bg-[radial-gradient(circle_at_25%_30%,#fff_0_4px,transparent_5px),radial-gradient(circle_at_70%_55%,#fff_0_4px,transparent_5px),linear-gradient(135deg,#d8e2d3,#e8dfd3_48%,#cfdbe1)]"><div className="absolute left-[20%] top-[28%] w-[55%] h-[40%] border-t-[5px] border-r-[5px] border-black rounded-[50%] rotate-6"/><div className="relative max-w-sm rounded-[24px] bg-white/95 backdrop-blur p-5 shadow-lg"><p className="text-xs uppercase tracking-wider text-neutral-400">Маршрут ALMA</p><p className="mt-2 font-semibold">{matchingPlaces.length} остановки · Петербург</p><p className="mt-2 text-sm text-neutral-500">После подключения маршрутных данных здесь будет настоящая интерактивная линия между точками.</p></div></div></div>
 <div className="mt-6 grid gap-4">{matchingPlaces.map((p,i)=><article key={p.id} className="grid sm:grid-cols-[150px_1fr_auto] gap-5 bg-white rounded-[28px] p-4 border border-black/5"><img src={p.image} alt={p.name} className="w-full h-32 object-cover rounded-[20px]"/><div className="py-2"><p className="text-xs text-neutral-400">Остановка {i+1} · {p.category}</p><h3 className="mt-1 text-2xl font-bold">{p.name}</h3><p className="mt-2 text-sm text-neutral-500">{p.why}</p></div><Link href={`/place/${p.id}`} className="self-center rounded-full bg-black text-white px-5 py-3 text-sm">Подробнее →</Link></article>)}</div>
 <div className="mt-6 grid lg:grid-cols-2 gap-5"><div className="rounded-[30px] bg-[#171717] text-white p-7"><p className="text-xs uppercase tracking-[.16em] text-white/45">ALMA · маршрут с приоритетом безопасных точек</p><h3 className="mt-3 text-2xl font-bold">Дополнительный режим маршрута</h3><p className="mt-3 text-sm leading-6 text-white/65">В дальнейшем ALMA сможет отдавать приоритет маршрутам рядом с проверенными заведениями и точками помощи. Кодовые слова или фразы будем показывать только там, где программа подтверждена самим заведением или надёжным источником. Это дополнительная помощь, а не гарантия безопасности.</p><div className="mt-5 rounded-2xl bg-white/10 p-4 text-sm">Щит на карте = проверенная точка помощи ALMA</div></div>
 {(company==="Пара"||mood==="Романтика")&&<div className="rounded-[30px] bg-[#eadfd8] p-7"><p className="text-xs uppercase tracking-[.16em] text-neutral-500">Свидание</p><h3 className="mt-3 text-2xl font-bold">Отправить приглашение?</h3><p className="mt-3 text-sm leading-6 text-neutral-600">Можно поделиться приглашением, не раскрывая заранее все точки сюрприза.</p>{!invite?<button onClick={()=>setInvite(true)} className="mt-5 rounded-full bg-black text-white px-6 py-3 text-sm">Да, подготовить приглашение</button>:<div className="mt-5 rounded-[20px] bg-white p-5"><p className="text-xs text-neutral-400">ПРИГЛАШЕНИЕ ALMA</p><p className="mt-2 font-semibold">У меня есть план для нас ✦</p><p className="mt-2 text-sm text-neutral-500">Место встречи и детали откроются после подтверждения приглашения.</p></div>}</div>}</div>
 <div className="mt-6 flex flex-wrap gap-3"><Link href="/map" className="rounded-full bg-black text-white px-6 py-3.5 font-medium">Открыть карту ALMA →</Link><button onClick={reset} className="rounded-full border border-black/10 bg-white px-6 py-3.5">Собрать другой маршрут</button></div></section>}
 </section></main>;
}
