"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { places } from "@/data/places";
import PurchasedRouteStory from "@/components/PurchasedRouteStory";

const moods=["Спокойно","Романтика","Вдохновиться","Удивиться"];
const budgets=["Бесплатно","300–1500 ₽","2000–5000 ₽","6000–10000 ₽","от 10000 ₽"];
const companies=["Один","Пара","Друзья","Семья"];
const durations=["До 1 часа","1–2 часа","2–4 часа","Полдня"];
const interests=["Искусство","Вкусно поесть","Прогулки","Необычные места","Развлечения","Романтика"];
type Step=1|2|3|4|5|6;
const DRAFT_KEY="alma-surprise-draft",TEST_PURCHASE_KEY="alma-test-route-purchase";
const matchesInterest=(p:(typeof places)[number],interest:string)=>{const c=p.category.toLowerCase();if(interest==="Искусство")return c.includes("искус")||c.includes("музей");if(interest==="Вкусно поесть")return c.includes("каф")||c.includes("ресторан")||c.includes("коф")||c.includes("бар");if(interest==="Прогулки")return c.includes("прогул")||c.includes("парк")||c.includes("пространство")||c.includes("отдых");if(interest==="Необычные места")return c.includes("необыч")||c.includes("скрыт")||c.includes("андеграунд")||c.includes("современн")||c.includes("архитект");if(interest==="Развлечения")return c.includes("развлеч")||c.includes("интерактив");if(interest==="Романтика")return p.mood==="Романтика"||c.includes("прогул")||c.includes("отдых");return false};
export default function SurprisePage(){
 const [step,setStep]=useState<Step>(1),[mood,setMood]=useState(""),[budget,setBudget]=useState(""),[company,setCompany]=useState(""),[duration,setDuration]=useState(""),[selectedInterests,setSelectedInterests]=useState<string[]>([]),[generated,setGenerated]=useState(false),[testPurchased,setTestPurchased]=useState(false);
 const toggleInterest=(v:string)=>setSelectedInterests(x=>x.includes(v)?x.filter(i=>i!==v):[...x,v]);
 const matchingPlaces=useMemo(()=>{const score=(p:(typeof places)[number])=>(p.mood===mood?4:0)+(p.budget===budget?3:0)+(p.company.includes(company)?3:0)+(p.duration===duration?2:0)+selectedInterests.reduce((s,i)=>s+(matchesInterest(p,i)?(i==="Романтика"?4:3):0),0);const ranked=[...places].sort((a,b)=>score(b)-score(a));const max=duration==="Полдня"?5:duration==="2–4 часа"?4:duration==="1–2 часа"?3:2;const chosen:typeof places=[];for(const interest of selectedInterests){const p=ranked.find(x=>matchesInterest(x,interest)&&!chosen.some(y=>y.id===x.id));if(p)chosen.push(p);if(chosen.length>=max)break;}for(const p of ranked){if(chosen.length>=max)break;if(!chosen.some(x=>x.id===p.id))chosen.push(p);}return chosen;},[mood,budget,company,duration,selectedInterests]);
 const can=()=>step===1?!!mood:step===2?!!company:step===3?!!budget:step===4?!!duration:step===5?selectedInterests.length>0:true;
 const Option=({value,current,set}:{value:string;current:string;set:(v:string)=>void})=><button type="button" onClick={()=>set(value)} className={`rounded-[22px] border px-5 py-5 text-left text-base sm:text-lg font-medium transition ${current===value?"bg-black border-black text-white":"bg-white border-black/10 hover:border-black/30"}`}><span className="flex justify-between"><span>{value}</span><span>{current===value?"✓":""}</span></span></button>;
 const question=step===1?["Какое у тебя настроение?",moods,mood,setMood]:step===2?["Какая сегодня компания?",companies,company,setCompany]:step===3?["Какой бюджет?",budgets,budget,setBudget]:["Сколько времени есть?",durations,duration,setDuration] as any;
 const draft=()=>({mood,budget,company,duration,interests:selectedInterests,placeIds:matchingPlaces.map(p=>p.id),createdAt:new Date().toISOString()});
 const saveDraft=()=>{try{localStorage.setItem(DRAFT_KEY,JSON.stringify(draft()))}catch{}};
 const testPurchase=()=>{try{localStorage.setItem(DRAFT_KEY,JSON.stringify(draft()));localStorage.setItem(TEST_PURCHASE_KEY,JSON.stringify({id:`TEST-${Date.now()}`,product:"route-199",amount:199,currency:"RUB",status:"test_paid",route:draft(),paidAt:new Date().toISOString()}))}catch{}setTestPurchased(true);setTimeout(()=>document.getElementById("purchased-route")?.scrollIntoView({behavior:"smooth"}),50)};
 const reset=()=>{try{localStorage.removeItem(DRAFT_KEY);localStorage.removeItem(TEST_PURCHASE_KEY)}catch{}setGenerated(false);setTestPurchased(false);setStep(1);setMood("");setBudget("");setCompany("");setDuration("");setSelectedInterests([]);window.scrollTo({top:0,behavior:"smooth"})};
 return <main className="min-h-screen bg-[#f7f4ef] pt-32 pb-24"><section className="max-w-6xl mx-auto px-4 sm:px-6"><div className="max-w-3xl"><div className="inline-flex rounded-full bg-black text-white px-4 py-2 text-sm">✦ ALMA · Удиви меня</div><h1 className="mt-7 text-5xl sm:text-6xl lg:text-7xl font-bold tracking-tight leading-[.98]">Соберём твой<br/>Петербург</h1><p className="mt-6 max-w-2xl text-lg sm:text-xl leading-8 text-neutral-500">Ответь на несколько вопросов бесплатно. ALMA соберёт персональный сценарий прогулки — готовый маршрут можно открыть за 199 ₽.</p></div>
 {!generated&&<div className="mt-14 sm:mt-20"><div className="flex justify-between mb-3 text-sm text-neutral-500"><span>Шаг {step} из 6</span><span>{Math.round(step/6*100)}%</span></div><div className="h-1.5 rounded-full bg-black/5 overflow-hidden"><div className="h-full bg-black" style={{width:`${step/6*100}%`}}/></div><div className="mt-8 rounded-[40px] bg-[#ebe6de] p-6 sm:p-10">{step<6?<>{step===5?<><p className="text-sm text-neutral-500">Можно выбрать несколько</p><h2 className="mt-3 text-3xl sm:text-4xl font-bold">Что добавить в маршрут?</h2><p className="mt-3 text-sm text-neutral-500">Каждый выбор станет отдельной частью сценария — например, искусство → вкусно поесть → прогулка → романтичный финал.</p><div className="mt-8 grid sm:grid-cols-2 gap-3">{interests.map(v=>{const active=selectedInterests.includes(v);return <button key={v} type="button" onClick={()=>toggleInterest(v)} className={`rounded-[22px] border px-5 py-5 text-left text-lg font-medium ${active?"bg-black border-black text-white":"bg-white border-black/10"}`}><span className="flex justify-between"><span>{v}</span><span>{active?"✓":"＋"}</span></span></button>})}</div>{selectedInterests.length>0&&<p className="mt-4 text-sm font-medium">Выбрано: {selectedInterests.length}</p>}</>:<><p className="text-sm text-neutral-500">Удиви меня</p><h2 className="mt-3 text-3xl sm:text-4xl font-bold">{question[0]}</h2><div className="mt-8 grid sm:grid-cols-2 gap-3">{(question[1] as string[]).map(v=><Option key={v} value={v} current={question[2]} set={question[3]}/>)}</div></>}</>:<><p className="text-sm text-neutral-500">Почти готово</p><h2 className="mt-3 text-3xl sm:text-4xl font-bold">Собрать твой маршрут?</h2><div className="mt-8 grid sm:grid-cols-2 gap-3">{[["Настроение",mood],["Компания",company],["Бюджет",budget],["Время",duration],["Сценарий",selectedInterests.join(" → ")]].map(([l,v])=><div key={l} className="rounded-[22px] bg-white p-5"><p className="text-xs uppercase tracking-wider text-neutral-400">{l}</p><p className="mt-2 font-semibold">{v}</p></div>)}</div><p className="mt-6 text-sm text-neutral-500">Названия точек, фотографии и полный сценарий откроются после покупки.</p></>}<div className="mt-9 flex justify-between gap-3"><button disabled={step===1} onClick={()=>setStep((step-1) as Step)} className="rounded-full px-6 py-3.5 border border-black/10 disabled:opacity-30">← Назад</button>{step<6?<button disabled={!can()} onClick={()=>setStep((step+1) as Step)} className="rounded-full bg-black text-white px-7 py-3.5 disabled:opacity-25">Дальше →</button>:<button onClick={()=>setGenerated(true)} className="rounded-full bg-black text-white px-8 py-3.5">✦ Собрать маршрут</button>}</div></div></div>}
 {generated&&<section className="mt-16"><div className="max-w-3xl"><p className="text-xs uppercase tracking-[.22em] text-neutral-500">ALMA собрала твой маршрут</p><h2 className="mt-4 text-4xl sm:text-6xl font-bold tracking-tight">Есть план ✦</h2><p className="mt-4 text-lg text-neutral-500">{mood} · {company} · {duration} · {selectedInterests.join(" → ")}</p></div>{testPurchased?<div id="purchased-route"><PurchasedRouteStory stops={matchingPlaces} romantic={company==="Пара"||mood==="Романтика"||selectedInterests.includes("Романтика")} onReset={reset}/></div>:<><div className="mt-9 grid lg:grid-cols-[1.15fr_.85fr] gap-5"><div className="relative overflow-hidden rounded-[34px] min-h-[430px] bg-[linear-gradient(135deg,#d8e2d3,#e8dfd3_48%,#cfdbe1)] border border-black/5"><div className="absolute inset-0 bg-black/10 backdrop-blur-[6px]"/><div className="relative min-h-[430px] flex items-center justify-center p-8"><div className="max-w-sm text-center rounded-[28px] bg-white/95 p-7 shadow-xl"><p className="text-xs uppercase tracking-[.18em] text-neutral-400">Маршрут скрыт</p><h3 className="mt-2 text-2xl font-bold">{matchingPlaces.length} остановки в Петербурге</h3><p className="mt-3 text-sm leading-6 text-neutral-500">Фото, названия мест, последовательность и переходы откроются после покупки.</p></div></div></div><aside className="rounded-[34px] bg-black text-white p-7 sm:p-9 flex flex-col"><p className="text-xs uppercase tracking-[.18em] text-white/45">Твой маршрут ALMA</p><h3 className="mt-4 text-3xl font-bold">Открыть весь маршрут</h3><div className="mt-7 space-y-3 text-sm text-white/70"><p>✓ {matchingPlaces.length} остановки в сценарии</p><p>✓ Фото и порядок точек</p><p>✓ Сколько времени провести в каждой</p><p>✓ Как добраться до следующей</p><p>✓ Что надеть и интересные детали</p>{(company==="Пара"||mood==="Романтика"||selectedInterests.includes("Романтика"))&&<p>✓ Подсказки для свидания без спойлеров</p>}</div><div className="mt-auto pt-10"><p className="text-4xl font-bold">199 ₽</p><Link onClick={saveDraft} href="/login?next=/surprise&product=route-199" className="mt-6 block text-center rounded-full bg-white text-black px-6 py-4 font-semibold">Открыть маршрут · 199 ₽</Link><button type="button" onClick={testPurchase} className="mt-3 w-full rounded-full border border-white/20 px-6 py-3.5 text-sm font-semibold">Тестовая покупка · 0 ₽</button><p className="mt-3 text-center text-xs text-white/40">Тестовый режим ничего не списывает.</p></div></aside></div></>}</section>}</section></main>;
}
