"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { dogFriendlyPlaces } from "@/data/dogFriendlyPlaces";
import { mapPlaces } from "@/data/mapPlaces";

export default function DogFriendlyPage() {
  const [category, setCategory] = useState("Все места");
  const [district, setDistrict] = useState("Все районы");
  const categories = ["Все места", ...Array.from(new Set(dogFriendlyPlaces.map((place) => place.category)))];
  const districts = ["Все районы", ...Array.from(new Set(dogFriendlyPlaces.map((place) => place.district)))];
  const filtered = useMemo(() => dogFriendlyPlaces.filter((place) => (category === "Все места" || place.category === category) && (district === "Все районы" || place.district === district)), [category, district]);
  const mapIdFor = (name: string) => mapPlaces.find((item) => item.name.toLowerCase() === name.toLowerCase())?.id;

  return (
    <main className="min-h-screen bg-[#f7f4ef] pt-32 sm:pt-36 pb-24 text-black"><section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="rounded-[36px] bg-[#dfe8d8] p-7 sm:p-10 lg:p-14"><p className="text-xs uppercase tracking-[0.22em] text-neutral-600">ALMA · Dog Friendly</p><h1 className="mt-4 max-w-3xl text-4xl sm:text-6xl lg:text-7xl font-bold tracking-tight leading-[0.96]">Петербург<br />вместе с собакой 🐾</h1><p className="mt-6 max-w-2xl text-base sm:text-lg text-neutral-700 leading-7">Проверенные места, куда можно прийти вместе с питомцем. В ALMA публикуем только заведения с подтверждённым рейтингом от 4,5 до 5,0.</p></div>
      <div className="mt-8 rounded-[28px] bg-white border border-black/5 p-5 sm:p-6"><div className="flex flex-col md:flex-row gap-4"><label className="flex-1 text-sm font-medium">Тип места<select value={category} onChange={(e) => setCategory(e.target.value)} className="mt-2 w-full rounded-2xl bg-[#f3f1ed] px-4 py-3 outline-none">{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label className="flex-1 text-sm font-medium">Район<select value={district} onChange={(e) => setDistrict(e.target.value)} className="mt-2 w-full rounded-2xl bg-[#f3f1ed] px-4 py-3 outline-none">{districts.map((item) => <option key={item}>{item}</option>)}</select></label></div></div>
      <div className="mt-8 grid md:grid-cols-2 gap-5 sm:gap-6">{filtered.map((place) => { const mapId = mapIdFor(place.name); return (<article key={place.id} className="overflow-hidden rounded-[30px] bg-white border border-black/5 shadow-sm">{place.imageUrl ? <div className="h-44 sm:h-48 overflow-hidden bg-[#ebe7df]"><img src={place.imageUrl} alt={`${place.name} — место, куда можно с собакой`} className="h-full w-full object-cover transition duration-500 hover:scale-[1.03]" loading="lazy" /></div> : <div className="h-44 sm:h-48 bg-[#ebe7df] flex items-center justify-center"><div className="text-center"><div className="text-5xl">🐾</div><p className="mt-3 text-sm font-medium text-neutral-500">Dog Friendly · ALMA</p></div></div>}<div className="p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.16em] text-neutral-400">{place.category}</p><h2 className="mt-2 text-2xl sm:text-3xl font-bold">{place.name}</h2></div><span className="shrink-0 rounded-full bg-[#dfe8d8] px-3 py-2 text-xs font-medium">🐾 Dog Friendly</span></div><div className="mt-4 flex flex-wrap items-center gap-2"><span className="rounded-full bg-black text-white px-3 py-2 text-sm font-semibold">★ {place.rating.toFixed(1)} / 5</span><span className="text-xs text-neutral-500">{place.ratingSource}{place.ratingCount ? ` · ${place.ratingCount.toLocaleString("ru-RU")} оценок` : ""}</span></div><p className="mt-4 text-neutral-500">{place.address}</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-[#f3f1ed] px-3 py-1.5 text-xs">{place.budget}</span><span className="rounded-full bg-[#f3f1ed] px-3 py-1.5 text-xs">{place.district}</span></div><div className="mt-6 rounded-[22px] bg-[#f7f4ef] p-5"><p className="text-sm font-semibold">Размер собаки</p><p className="mt-1 text-neutral-600">{place.dogSize}</p><p className="mt-4 text-sm font-semibold">Условия</p><p className="mt-1 text-sm leading-6 text-neutral-600">{place.dogRules}</p></div><div className="mt-5 flex items-center justify-between gap-4"><span className="text-xs text-neutral-400">Проверено ALMA: {place.verifiedAt}</span>{mapId && <Link href={`/map?place=${mapId}`} title="На карте" aria-label={`${place.name} на карте ALMA`} className="shrink-0 inline-flex h-12 w-12 items-center justify-center rounded-full bg-black text-white transition hover:scale-105"><svg viewBox="0 0 24 24" width="23" height="23" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg></Link>}</div></div></article>);})}</div>
      <div className="mt-10 rounded-[28px] bg-black text-white p-6 sm:p-8"><p className="text-sm font-semibold">Правило ALMA</p><p className="mt-3 max-w-4xl text-sm sm:text-base leading-7 text-white/70">Публикуем заведения только с подтверждённой оценкой от 4,5 до 5,0 по пятибалльной шкале.</p></div>
    </section></main>
  );
}
