"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function CheckoutPage(){
 const router=useRouter();
 const [number,setNumber]=useState("");
 const [expiry,setExpiry]=useState("");
 const [cvc,setCvc]=useState("");
 const [name,setName]=useState("");
 const ready=number.replace(/\D/g,"").length===16&&expiry.length>=4&&cvc.length>=3&&name.trim().length>1;
 const pay=()=>{if(!ready)return;try{localStorage.setItem("alma-test-route-purchase",JSON.stringify({id:`TEST-${Date.now()}`,product:"route-199",amount:199,currency:"RUB",status:"test_paid",paidAt:new Date().toISOString()}));}catch{}router.push("/surprise?purchase=test-success");};
 return <main className="min-h-screen bg-[#f7f4ef] pt-28 pb-16 px-4"><div className="mx-auto max-w-[520px]"><Link href="/surprise" className="text-sm text-neutral-500">← Вернуться к маршруту</Link><div className="mt-5 rounded-[34px] bg-white p-7 sm:p-9 shadow-xl border border-black/5"><p className="text-xs uppercase tracking-[.2em] text-neutral-400">ALMA · тест оплаты</p><h1 className="mt-3 text-3xl font-bold">Маршрут · 199 ₽</h1><p className="mt-2 text-sm leading-6 text-neutral-500">Так будет выглядеть шаг оплаты картой. Сейчас это безопасный тест: данные никуда не отправляются, деньги не списываются.</p><div className="mt-5 rounded-2xl bg-[#f2eee7] p-4 text-xs leading-5 text-neutral-600"><b>Для теста используй только вымышленные данные.</b><br/>Например: 1111 1111 1111 1111 · 12/30 · 123 · TEST USER</div><label className="mt-7 block text-xs font-medium text-neutral-500">Номер карты</label><input value={number} onChange={e=>setNumber(e.target.value.replace(/[^\d ]/g,"").slice(0,19))} placeholder="1111 1111 1111 1111" inputMode="numeric" autoComplete="off" className="mt-2 w-full rounded-2xl border border-black/20 px-4 py-4 outline-none focus:border-black"/><div className="mt-4 grid grid-cols-2 gap-3"><div><label className="block text-xs font-medium text-neutral-500">Срок</label><input value={expiry} onChange={e=>setExpiry(e.target.value.slice(0,5))} placeholder="12/30" autoComplete="off" className="mt-2 w-full rounded-2xl border border-black/20 px-4 py-4 outline-none focus:border-black"/></div><div><label className="block text-xs font-medium text-neutral-500">CVC</label><input value={cvc} onChange={e=>setCvc(e.target.value.replace(/\D/g,"").slice(0,3))} placeholder="123" inputMode="numeric" autoComplete="off" className="mt-2 w-full rounded-2xl border border-black/20 px-4 py-4 outline-none focus:border-black"/></div></div><label className="mt-4 block text-xs font-medium text-neutral-500">Имя на карте</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="TEST USER" autoComplete="off" className="mt-2 w-full rounded-2xl border border-black/20 px-4 py-4 outline-none focus:border-black"/><button type="button" disabled={!ready} onClick={pay} className="mt-6 w-full rounded-full bg-black px-6 py-4 font-semibold text-white disabled:opacity-25">Тестово оплатить 199 ₽</button><p className="mt-4 text-center text-xs leading-5 text-neutral-400">В рабочей версии поля карты будет обрабатывать платёжный провайдер. ALMA не должна хранить номер карты или CVC.</p></div></div></main>;
}
