"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

export default function CheckoutPage(){
 const [step,setStep]=useState<"start"|"waiting"|"sent">("start");
 const reference=useMemo(()=>`ALMA-${Date.now().toString(36).toUpperCase().slice(-6)}`,[]);
 const requestDetails=()=>setStep("waiting");
 const confirmSent=()=>{try{localStorage.setItem("alma-transfer-request",JSON.stringify({reference,product:"route-199",amount:199,currency:"RUB",status:"awaiting_manual_confirmation",createdAt:new Date().toISOString()}));}catch{}setStep("sent");};
 return <main className="min-h-screen bg-[#f7f4ef] pt-28 pb-16 px-4"><div className="mx-auto max-w-[520px]"><Link href="/surprise" className="text-sm text-neutral-500">← Вернуться к маршруту</Link><div className="mt-5 rounded-[34px] bg-white p-7 sm:p-9 shadow-xl border border-black/5"><p className="text-xs uppercase tracking-[.2em] text-neutral-400">ALMA · оплата</p><h1 className="mt-3 text-3xl font-bold">Маршрут · 199 ₽</h1><p className="mt-3 text-sm leading-6 text-neutral-500">Оплата переводом. ALMA не запрашивает номер карты, срок действия или CVC.</p>
 {step==="start"&&<><div className="mt-7 rounded-[24px] bg-[#f2eee7] p-5"><p className="text-xs uppercase tracking-[.16em] text-neutral-400">Способ оплаты</p><h2 className="mt-2 text-xl font-bold">Перевод · 199 ₽</h2><p className="mt-3 text-sm leading-6 text-neutral-600">Нажми ниже, чтобы создать запрос на оплату. Полные банковские реквизиты не хранятся в публичном коде ALMA.</p></div><button type="button" onClick={requestDetails} className="mt-6 w-full rounded-full bg-black px-6 py-4 font-semibold text-white hover:opacity-85 transition">Получить реквизиты →</button></>}
 {step==="waiting"&&<><div className="mt-7 rounded-[24px] bg-[#f2eee7] p-5"><p className="text-xs uppercase tracking-[.16em] text-neutral-400">Запрос создан</p><h2 className="mt-2 text-xl font-bold">199 ₽ · {reference}</h2><p className="mt-3 text-sm leading-6 text-neutral-600">Для безопасного запуска реквизиты должны приходить через отдельный защищённый канал или платёжную ссылку банка. Мы не показываем номер карты из исходного кода сайта.</p><div className="mt-4 rounded-2xl bg-white p-4 text-sm leading-6"><b>Комментарий к переводу:</b><br/>{reference}</div></div><div className="mt-5 rounded-[20px] border border-black/10 p-4"><p className="text-sm font-semibold">После перевода</p><p className="mt-2 text-sm leading-6 text-neutral-500">Нажми «Я перевёл». Это отправит заявку в статус ожидания проверки. Маршрут не откроется автоматически, пока платёж не подтверждён.</p></div><button type="button" onClick={confirmSent} className="mt-6 w-full rounded-full bg-black px-6 py-4 font-semibold text-white hover:opacity-85 transition">Я перевёл · отправить на проверку</button></>}
 {step==="sent"&&<><div className="mt-7 rounded-[24px] bg-black p-6 text-white"><p className="text-xs uppercase tracking-[.16em] text-white/45">Оплата на проверке</p><h2 className="mt-2 text-2xl font-bold">Заявка принята</h2><p className="mt-3 text-sm leading-6 text-white/65">Номер заявки: {reference}. После реального подтверждения платежа ALMA откроет купленный маршрут.</p></div><Link href="/surprise" className="mt-6 block w-full rounded-full border border-black/15 px-6 py-4 text-center font-semibold hover:bg-black hover:text-white transition">Вернуться к маршруту</Link></>}
 <p className="mt-5 text-center text-xs leading-5 text-neutral-400">Не отправляй через ALMA данные банковской карты. Для автоматической оплаты позже подключим платёжного провайдера.</p></div></div></main>;
}
