"use client";
import { useEffect, useState } from "react";
type Stats={total:number;today:number;week:number;month:number;lastRegistration:number|null;pageViews:{total:number;today:number;week:number;month:number};pages:{path:string;views:number}[]};
const names:Record<string,string>={"/":"Главная","/map":"События","/dog-friendly":"С собакой","/photozones":"Фотолокации","/collections":"Подборки","/about":"О проекте","/favorites":"Избранное","/surprise":"Готовый маршрут","/login":"Вход / регистрация"};
export default function AdminStatsPage(){
 const [stats,setStats]=useState<Stats|null>(null);const [error,setError]=useState("");
 const load=()=>fetch("/api/admin/stats",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Ошибка");setStats(d);setError("")}).catch(e=>setError(e.message));
 useEffect(()=>{load();const id=setInterval(load,30000);return()=>clearInterval(id)},[]);
 const card=(title:string,value:number,caption:string)=><div className="rounded-[24px] bg-white p-5 sm:p-6 shadow-[0_10px_35px_rgba(0,0,0,.04)]"><p className="text-[13px] font-semibold text-neutral-800">{title}</p><p className="mt-2 text-4xl font-bold tracking-tight">{value}</p><p className="mt-2 text-xs leading-5 text-neutral-500">{caption}</p></div>;
 return <main className="min-h-screen bg-[#f7f4ef] px-4 pt-28 pb-16 text-black"><section className="mx-auto max-w-5xl"><p className="text-xs uppercase tracking-[.22em] text-neutral-500">ALMA · только для владельца</p><div className="mt-3 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-4xl sm:text-6xl font-bold tracking-tight">Статистика ALMA</h1><p className="mt-3 text-sm text-neutral-500">Данные обновляются автоматически каждые 30 секунд.</p></div></div>{error&&<div className="mt-8 rounded-3xl bg-white p-6">{error}</div>}{!error&&!stats&&<div className="mt-8 text-neutral-500">Загружаю статистику…</div>}{stats&&<><h2 className="mt-9 text-xl font-bold">Пользователи</h2><div className="mt-4 grid grid-cols-2 lg:grid-cols-4 gap-3">{card("Всего аккаунтов",stats.total,"Все зарегистрированные пользователи")}{card("Новых сегодня",stats.today,"Регистрации за последние 24 часа")}{card("Новых за 7 дней",stats.week,"Регистрации за последнюю неделю")}{card("Новых за 30 дней",stats.month,"Регистрации за последний месяц")}</div><p className="mt-4 text-sm text-neutral-500">{stats.lastRegistration?"Последняя регистрация: "+new Date(stats.lastRegistration*1000).toLocaleString("ru-RU",{timeZone:"Europe/Moscow"}):"Регистраций пока нет"}</p><h2 className="mt-10 text-xl font-bold">Посещения страниц</h2><div className="mt-4 grid grid-cols-2 lg:grid-cols-4 gap-3">{card("Просмотров сегодня",stats.pageViews.today,"Сколько страниц открыли за 24 часа")}{card("За 7 дней",stats.pageViews.week,"Просмотры страниц за неделю")}{card("За 30 дней",stats.pageViews.month,"Просмотры страниц за месяц")}{card("Всего просмотров",stats.pageViews.total,"С момента включения этой статистики")}</div><div className="mt-5 overflow-hidden rounded-[26px] bg-white"><div className="border-b border-black/5 px-5 py-4"><h3 className="font-bold">Какие страницы смотрят</h3><p className="mt-1 text-xs text-neutral-500">Количество открытий каждой страницы с момента включения счётчика</p></div>{stats.pages.length===0?<p className="p-5 text-sm text-neutral-500">Посещения начнут появляться после публикации обновления.</p>:<div>{stats.pages.map((p,i)=><div key={p.path} className="flex items-center justify-between gap-4 border-b border-black/5 px-5 py-4 last:border-0"><div className="min-w-0"><p className="font-semibold">{i+1}. {names[p.path]||p.path}</p><p className="mt-0.5 truncate text-xs text-neutral-400">{p.path}</p></div><div className="shrink-0 text-right"><p className="text-2xl font-bold">{p.views}</p><p className="text-[11px] text-neutral-400">просмотров</p></div></div>)}</div>}</div></>}</section></main>;
}